site_name: Daily dose of Python
edit_uri: edit/main/docs/
repo_url: https://github.com/jerry-git/daily-dose-of-python

theme:
  name: material
  features:
    - navigation.expand
  palette:
    - scheme: default
      primary: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - attr_list:
  - md_in_html:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.details:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences:


plugins:
  - search:
  - tags:
      tags_template: docs/theme/tags.md.template
      tags_folder: .tmp

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/JerryPussinen
      name: Jerry on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jerry-pussinen-20a3a7140/
      name: Jerry on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/jerry-git
      name: Jerry on GitHub
