site_name: Daily dose of Python
edit_uri: edit/main/docs/
repo_url: https://github.com/jerry-git/daily-dose-of-python
site_url: https://jerry-git.github.io/daily-dose-of-python/

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.expand
  palette:
    - scheme: default
      primary: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/brands/python
  favicon: img/favicon.png

nav:
  - Home: index.md
  - Categories: tags.md
  - Doses:
      - doses/1.md
      - doses/2.md
      - doses/3.md
      - doses/4.md
      - doses/5.md
      - doses/6.md
      - doses/7.md
      - doses/8.md
      - doses/9.md
      - doses/10.md
      - doses/11.md
      - doses/12.md

markdown_extensions:
  - attr_list:
  - md_in_html:
  - meta:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.details:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences:


plugins:
  - search:
  - tags:
      tags_template: docs/theme/tags.md.template
      tags_folder: .tmp

extra:
  analytics:
    provider: custom
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/JerryPussinen
      name: Jerry on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jerry-pussinen-20a3a7140/
      name: Jerry on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/jerry-git
      name: Jerry on GitHub
  default_meta_tags:
    og_image: img/daily-dose-of-python.png
    twitter:
      title: Daily dose of Python
      description: Slightly more advanced Python tips and tricks in easy to digest format.
      image: img/daily-dose-of-python.png
